version: '3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
  order-db:
    image: quay.io/debezium/example-postgres:2.1.1.Final
    ports:
     - 5433:5432
    healthcheck:
      test: "pg_isready -U postgresuser -d orderdb"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
     - POSTGRES_USER=postgresuser
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=orderdb