spring:
   datasource:
      initialization-mode: always
      url: jdbc:h2:mem:test_db;MODE=PostgreSQL
      driverClassName: org.h2.Driver
      username: sa
      password: password
      continueOnError: true
   h2:
      console:
         enabled: true
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect